- build.gradle
- src/main/kotlin/scenery/GenericTexture.kt
- src/main/kotlin/scenery/HasGeometry.kt
- src/main/kotlin/scenery/Material.kt
- src/main/kotlin/scenery/Node.kt
- src/main/kotlin/scenery/Renderable.kt
- src/main/kotlin/scenery/Scene.kt
- src/main/kotlin/scenery/Settings.kt
- src/main/kotlin/scenery/controls/ClearGLInputHandler.kt
- src/main/kotlin/scenery/controls/OpenVRInput.kt
- src/main/kotlin/scenery/rendermodules/opengl/DeferredLightingRenderer.kt
- src/main/kotlin/scenery/rendermodules/opengl/OpenGLShaderPreference.kt
- src/main/kotlin/scenery/repl/REPL.kt
- src/main/resources/scenery/rendermodules/opengl/shaders/Combiner.frag
- src/main/resources/scenery/rendermodules/opengl/shaders/DefaultDeferred.vert
- src/main/resources/scenery/repl/startup.js
- src/test/kotlin/scenery/tests/examples/BloodCellsExample.kt
- src/test/kotlin/scenery/tests/examples/BoxedProteinExample.kt
- src/test/kotlin/scenery/tests/examples/LineExample.kt
- src/test/kotlin/scenery/tests/examples/OpenVRExample.kt
- src/test/kotlin/scenery/tests/examples/SponzaExample.kt
- src/test/kotlin/scenery/tests/examples/TexturedCubeExample.kt
This PR integrates preliminary OpenVR support. So far, we're able to load the OpenVR library and query some details about the attached HMD.
> Preliminary OpenVR integration

- .travis.yml
This PR fixes the OSX build on Travis, with configuration as suggested by the awesome Travis support guys.
> Fix OSX build on Travis

- src/main/kotlin/scenery/BoundingBox.kt
- src/main/kotlin/scenery/Box.kt
- src/main/kotlin/scenery/BufferUtils.kt
- src/main/kotlin/scenery/Camera.kt
- src/main/kotlin/scenery/HasGeometry.kt
- src/main/kotlin/scenery/Line.kt
- src/main/kotlin/scenery/Mesh.kt
- src/main/kotlin/scenery/Node.kt
- src/main/kotlin/scenery/Plane.kt
- src/main/kotlin/scenery/SceneryDefaultApplication.kt
- src/main/kotlin/scenery/SceneryDefaultJPanelApplication.kt
- src/main/kotlin/scenery/Sphere.kt
- src/main/kotlin/scenery/controls/ClearGLInputHandler.kt
- src/main/kotlin/scenery/controls/behaviours/ArcballCameraControl.kt
- src/main/kotlin/scenery/controls/behaviours/FPSCameraControl.kt
- src/main/kotlin/scenery/controls/behaviours/SelectCommand.kt
- src/main/kotlin/scenery/fonts/SDFFontAtlas.kt
- src/main/kotlin/scenery/rendermodules/Renderer.kt
- src/main/kotlin/scenery/rendermodules/opengl/DeferredLightingRenderer.kt
- src/main/resources/scenery/rendermodules/opengl/shaders/BoundingBox.frag
- src/main/resources/scenery/rendermodules/opengl/shaders/Line.frag
- src/main/resources/scenery/rendermodules/opengl/shaders/Line.geom
- src/main/resources/scenery/rendermodules/opengl/shaders/Line.vert
- src/test/kotlin/scenery/tests/examples/LineExample.kt
- src/test/kotlin/scenery/tests/examples/VertexUpdateExample.kt
* Nodes now have a boundingBoxCoords property that stores their bounding box. This
property gets set e.g. by HasGeometry upon model loading
* there is a new BoundingBox object which makes use of the aforementioned property. This
object will display a customizable coordinate grid with axis labels
> WIP: Bounding boxes

- src/main/kotlin/scenery/GeometryType.kt
- src/main/kotlin/scenery/Line.kt
- src/main/kotlin/scenery/rendermodules/opengl/DeferredLightingRenderer.kt
- src/main/resources/scenery/rendermodules/opengl/shaders/Line.frag
- src/main/resources/scenery/rendermodules/opengl/shaders/Line.geom
- src/main/resources/scenery/rendermodules/opengl/shaders/Line.vert
- src/test/kotlin/scenery/tests/examples/LineExample.kt
* implements rendering of expanded lines via a geometry shader
* lines have properties edgeWidth, startColor, endColor and lineColor
* can be used as any other node and behave as a standard 3D object, however with constant width and with face-orientation towards the camera
* also adds LineExample, showing how to dynamically created Lines and illuminate them
> Line rendering

- README.md
- appveyor.yml
- build.gradle
- pom.xml
This PR adds the following:
* Appveyor CI support
* a pom.xml file for building via Maven
* introduces semver versioning also for scenery
> Maven & Appveyor support

- README.md
- pom.xml
- src/main/kotlin/graphics/scenery/HasGeometry.kt
- src/main/kotlin/graphics/scenery/utils/ExtractsNatives.kt
Bump to the next dev cycle, yay!
> Bump to 0.2.0-SNAPSHOT

- src/main/kotlin/graphics/scenery/Blending.kt
- src/main/kotlin/graphics/scenery/HasGeometry.kt
- src/main/kotlin/graphics/scenery/Material.kt
- src/main/kotlin/graphics/scenery/backends/RenderConfigReader.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanObjectState.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/test/tests/graphics/scenery/tests/examples/basic/SponzaExample.kt
This PR introduces per-object blending options, and has the blending options factored out into a class `Blending`, which contains subclasses `BlendOp` and `BlendFactor`.
> Per-object blending options

- pom.xml
- src/main/kotlin/graphics/scenery/GenericTexture.kt
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanTexture.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/VolumeExample.kt
Introduces loading of generic volume files (TIFF, RAW,...) via SCIFIO.
> Generic volume loading

- pom.xml
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/FXSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanBuffer.kt
- src/main/kotlin/graphics/scenery/utils/DirectWritableImage.kt
- src/main/kotlin/graphics/scenery/utils/SceneryPanel.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/ProceduralTextureExample.kt
- src/test/tests/graphics/scenery/tests/examples/basic/JavaFXTexturedCubeExample.kt
* fixes some JavaFX issues (thanks to @hanslovsky!)
* FXSwapchain: makes sure sharing buffers are available before handing them to JavaFX
* bumps spirvcrossj to 0.3.1
> JavaFX fixes

- src/main/kotlin/graphics/scenery/utils/SceneryPanel.kt
- src/test/tests/graphics/scenery/tests/examples/basic/JavaFXGridPaneExample.kt
- Add check for zero width/height
- Do not update if resizeTimer is still running
- Add example for use in GridPane with column/row constraints
PS: not breaking anymore
> Add fixes for SceneryPanel

- README.md
for MacBook Pro (Retina, Mid 2012)
> update the GPU compatibility table

- README.md
* adds AMD Radeon R5 230 on Windows
* adds Intel HD Graphics 4400 on Windows and Linux
> GPU compatibility table update (WIP)

- pom.xml
- src/main/kotlin/graphics/scenery/Settings.kt
- src/main/kotlin/graphics/scenery/backends/SceneryWindow.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/FXSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/OpenGLSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanFramebuffer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanPipeline.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/kotlin/graphics/scenery/controls/JavaFXMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/ArcballCameraControl.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/SelectCommand.kt
This updates the dependency on LWJGL to 3.1.6-SNAPSHOT, which improves the handling of nullable variables, improving Kotlin compatibility.
Also:
* Kotlin bumped to 1.2.20
* ffmpeg-platform bumped to 3.4.1-1.4
> Nullability changes

- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/UBO.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderProgram.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLUBO.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanPipeline.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanShaderModule.kt
- src/main/kotlin/graphics/scenery/utils/ExtractsNatives.kt
* fixes issue when rendering stereo with OpenGL where projection matrix instead of inverse were used in UBO for position reconstruction
* fixes issue where UBO buffer might be overstepped
* also extracts native libraries more efficiently
* ... and VulkanRenderer handles caching shader modules better
> OpenGL Lighting Fixes

- src/main/resources/graphics/scenery/backends/shaders/Volume.frag
- src/test/tests/graphics/scenery/tests/examples/basic/VolumeExample.kt
Fixes an issue where the OpenGL depth range was not taken into consideration correctly when reconstructing in the volume shader.
> Fix OpenGL volume/geometry intersections

- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/kotlin/graphics/scenery/controls/Hololens.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
- src/main/kotlin/graphics/scenery/controls/TrackedStereoGlasses.kt
- src/main/kotlin/graphics/scenery/controls/TrackerInput.kt
- src/main/kotlin/graphics/scenery/controls/VRPNTrackerInput.kt
- src/main/resources/graphics/scenery/backends/shaders/Volume.frag
- src/test/tests/graphics/scenery/tests/examples/advanced/EyeTrackingExample.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/VRControllerExample.kt
* adds support for [Windows Mixed Reality](https://www.microsoft.com/en-us/windows/windows-mixed-reality) VR headsets
* OpenVR: adds loading of controller etc. models originating from custom OpenVR drivers such as WMR
* OpenVR: rework eye pose model to support the different coord frames used by the HTC Vive and WMR headsets
* improves attaching VR controllers to nodes
* fixes and issue where Volume rendering in VR could be incorrect
> Windows Mixed Reality support

- src/main/kotlin/graphics/scenery/BoundingGrid.kt
- src/main/kotlin/graphics/scenery/BufferUtils.kt
- src/main/kotlin/graphics/scenery/HasGeometry.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/Display.kt
- src/main/kotlin/graphics/scenery/backends/RenderConfigReader.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanDevice.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanPipeline.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanShaderModule.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanTexture.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanUBO.kt
- src/main/kotlin/graphics/scenery/controls/MouseAndKeyHandlerBase.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
- src/main/kotlin/graphics/scenery/controls/TrackerInput.kt
This PR refactors some classes with better null checks and saner use, and makes a few style changes, and documents some classes better.
> Style/Nullability fixes & more documentation

- pom.xml
- src/main/kotlin/graphics/scenery/BufferUtils.kt
- src/main/kotlin/graphics/scenery/Material.kt
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/Renderer.kt
- src/main/kotlin/graphics/scenery/backends/UBO.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderModule.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLUBO.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanUBO.kt
- src/main/kotlin/graphics/scenery/controls/ScreenConfig.kt
- src/main/kotlin/graphics/scenery/utils/StickyBoolean.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/resources/graphics/scenery/controls/CAVEExample.yml
- src/test/tests/graphics/scenery/tests/unit/NodeTests.kt
- src/test/tests/graphics/scenery/tests/unit/UBOTests.kt
This PR introduces push-based rendering, where a new image is only renderer in case the scene changes or an input event is received. Activate by setting `Renderer.pushMode=true`.
> Push rendering

- src/main/kotlin/graphics/scenery/BoundingGrid.kt
- src/main/kotlin/graphics/scenery/HasGeometry.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/resources/graphics/scenery/backends/shaders/Volume.frag
* fixes volume bounding boxes
* makes the Volume shader obey the gamma parameter
> Volume bounding boxes

- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/Renderable.kt
… that might come from physical units. Propagates to children as regular Node transforms do.
> Introduces Renderable/Node.renderScale for global scales

- src/main/kotlin/graphics/scenery/Box.kt
- src/main/kotlin/graphics/scenery/Cone.kt
- src/main/kotlin/graphics/scenery/Cylinder.kt
- src/main/kotlin/graphics/scenery/Hub.kt
- src/main/kotlin/graphics/scenery/Icosphere.kt
- src/main/kotlin/graphics/scenery/Line.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/Plane.kt
- src/main/kotlin/graphics/scenery/Sphere.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/SelectCommand.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/PickerExample.kt
Brings the SelectCommand to the current bounding box architecture and adds PickerExample to demonstrate its functionality.
> Picker fixes

- src/main/kotlin/graphics/scenery/controls/JavaFXMouseAndKeyHandler.kt
This PR fixes scrolling and double-clicking with JavaFX.
> JavaFX scrolling & double-clicking fix

- src/main/kotlin/graphics/scenery/BoundingGrid.kt
- src/main/kotlin/graphics/scenery/Line.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/PointCloud.kt
- src/main/kotlin/graphics/scenery/PointLight.kt
- src/main/kotlin/graphics/scenery/ShaderMaterial.kt
- src/main/kotlin/graphics/scenery/Skybox.kt
- src/main/kotlin/graphics/scenery/TextBoard.kt
- src/main/kotlin/graphics/scenery/backends/ShaderNotFoundException.kt
- src/main/kotlin/graphics/scenery/backends/ShaderPackage.kt
- src/main/kotlin/graphics/scenery/backends/ShaderType.kt
- src/main/kotlin/graphics/scenery/backends/Shaders.kt
- src/main/kotlin/graphics/scenery/backends/SourceSPIRVPriority.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderModule.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderProgram.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanShaderModule.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/BloodCellsExample.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/MultiBoxInstancedExample.kt
**Breaking changes ahead!**
This PR refactors the way shaders are handled by Nodes. It removes Node.useClassDerivedShader and replaces it with a unified and more flexible system that also allows for shader factories.
> Shader refactoring

- src/main/kotlin/graphics/scenery/Line.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/Scene.kt
- src/main/kotlin/graphics/scenery/ShaderMaterial.kt
- src/main/kotlin/graphics/scenery/backends/ShaderPackage.kt
- src/main/kotlin/graphics/scenery/backends/Shaders.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanBufferAllocation.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
Introduces callbacks for the following events:
* a Node is added to the Scene (handled by Scene)
* a Node is removed from the Scene (handled by Scene)
* a Node's properties are updated (handled by Renderer)
> Introduce Node callbacks

- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/ArcballCameraControl.kt
Introduces moving targets for ArcBallCameraControl
> ArcballCameraControl: Support varying targets

- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/FXSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/resources/graphics/scenery/repl/startup.js
Adds support for switching renderers on-the-fly, addressing #106.
Renderers can be switched by calling `SceneryBase::replaceRenderer(String)` with either `VulkanRenderer` or `OpenGLRenderer` as parameter.
> Renderer switching

- src/main/kotlin/graphics/scenery/backends/Renderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/FXSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/HeadlessSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/OpenGLSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/Swapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/kotlin/graphics/scenery/utils/SceneryPanel.kt
Revamps Vulkan swapchain code to better fit with JavaFX integration.
> Swapchain revamp for JavaFX

- pom.xml
This PR makes the following changes:
* Update to the latest pom-scijava parent.
* Remove unneeded enforcer configuration.
* Remove redundant remote repositories.
> Miscellaneous POM improvements

- src/main/kotlin/graphics/scenery/Camera.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/PointLight.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/test/tests/graphics/scenery/tests/examples/basic/SponzaExample.kt
This PR introduces radar-based frustum culling.
> Frustum culling

- src/main/kotlin/graphics/scenery/Arrow.kt
- src/test/tests/graphics/scenery/tests/examples/basic/ArrowExample.kt
Hi,
this is the Arrow.kt that can draw simple arrows made of 7 line segments.
It is based on the code of Line.kt.
Disclaimer:
* I don't have kt compiler installed, just wrote it looking into code around to see how things are written... some body needs to compile and correct, I'm afraid.
* There are 2/3 TODOs left for which I haven't find the example.
> Adding arrows

- src/main/kotlin/graphics/scenery/Camera.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/BloodCellsExample.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/MultiBoxInstancedExample.kt
This PR fixes wrong instance updating which was caused by an (ab)use of CopyOnWriteArrayList.
> Instance update fixes

- src/main/resources/graphics/scenery/backends/shaders/DeferredLighting.frag
- src/main/resources/graphics/scenery/backends/shaders/Line.geom
- src/test/tests/graphics/scenery/tests/examples/basic/LineExample.kt
This PR introduces a special value, NaN, for normals. In case a NaN normal is encountered, it is assumed to be oriented towards the light source.
> Omnidirectional line lighting

- pom.xml
- src/main/kotlin/graphics/scenery/HasGeometry.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/OpenGLSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanTexture.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/GamepadCameraControl.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/GamepadMovementControl.kt
- src/main/kotlin/graphics/scenery/net/NodePublisher.kt
- src/main/kotlin/graphics/scenery/net/NodeSubscriber.kt
- src/main/kotlin/graphics/scenery/volumes/TransferFunction.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/resources/graphics/scenery/backends/DeferredShading.yml
- src/main/resources/graphics/scenery/backends/DeferredShadingStereo.yml
- src/main/resources/graphics/scenery/backends/shaders/DeferredLighting.frag
- src/main/resources/graphics/scenery/backends/shaders/HBAO.frag
- src/test/tests/graphics/scenery/tests/examples/cluster/DemoReelExample.kt
* improves material reading in HasGeometry
* SceneryBase: Initialize publisher/subscriber before scene init
* Node: make only fields `@Transient` that need to be
* VulkanRenderer: Improve framebuffer creation logging
* Volume: allow specification of data type when preloading into main memory
* Volume: remove locking code which is unnecessary due to use of ConcurrentHashMap
* OpenGLSwapchain: create backing images in right size
* DeferredLighting/HBAO shaders: fix incorrect Z reconstruction
> Clustering updates

- src/main/kotlin/graphics/scenery/Cone.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanPipeline.kt
- src/test/tests/graphics/scenery/tests/examples/basic/TexturedCubeExample.kt
Improves the cone class with better texture coordinates and customizeable default direction.
> Better cones

- src/main/kotlin/graphics/scenery/BufferUtils.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/TextBoard.kt
- src/main/kotlin/graphics/scenery/backends/RenderConfigReader.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderModule.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderProgram.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/compute/OpenCLContext.kt
- src/main/kotlin/graphics/scenery/controls/SwingMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/fonts/SDFFontAtlas.kt
- src/main/kotlin/graphics/scenery/utils/Statistics.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
Adds more nullability fixes for more idiomatic Kotlin code.
> More nullability fixes

- src/main/kotlin/graphics/scenery/Box.kt
- src/main/kotlin/graphics/scenery/HasGeometry.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/OrientedBoundingBox.kt
- src/main/kotlin/graphics/scenery/PointCloud.kt
- src/main/kotlin/graphics/scenery/net/NodePublisher.kt
- src/main/kotlin/graphics/scenery/net/NodeSubscriber.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
This PR is in support of https://github.com/scenerygraphics/sciview/tree/line3d-demo.
> OrientedBoundingBox refactor

- pom.xml
- src/main/kotlin/graphics/scenery/backends/JavaFXStage.kt
- src/main/kotlin/graphics/scenery/backends/ResizeHandler.kt
- src/main/kotlin/graphics/scenery/backends/SceneryWindow.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/FXSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/HeadlessSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/OpenGLSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/Swapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/SwapchainParameters.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/SwingSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/kotlin/graphics/scenery/controls/CanHandleInputFor.kt
- src/main/kotlin/graphics/scenery/controls/GLFWMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/controls/InputHandler.kt
- src/main/kotlin/graphics/scenery/controls/JOGLMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/controls/JavaFXMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/controls/MouseAndKeyHandlerBase.kt
- src/main/kotlin/graphics/scenery/utils/SceneryFXPanel.kt
- src/main/kotlin/graphics/scenery/utils/SceneryJPanel.kt
- src/main/kotlin/graphics/scenery/utils/SceneryPanel.kt
This PR modularises InputHandlers, Swapchains, and SceneryPanels more such that they can be initialised dynamically (via reflection).
> Input and swapchain modularisation

- src/main/kotlin/graphics/scenery/utils/SystemHelpers.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/BloodCellsExample.kt
This PR fixes some issues with encoding string paths to Java Path objects, especially when the strings contain spaces.
> Path encoding fixes

- pom.xml
- src/main/kotlin/graphics/scenery/GenericTexture.kt
- src/main/kotlin/graphics/scenery/TextBoard.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanTexture.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/kotlin/graphics/scenery/volumes/bdv/SceneryContext.kt
This PR introduces support for all the repeat modes supported by OpenGL and Vulkan.
> Support for more texture repeat modes

- src/main/kotlin/graphics/scenery/Icosphere.kt
This PR fixes an issue where UV coordinates for the icosphere were generated wrongly, and in addition fixes texture seams that might occur if icosphere vertices are not duplicated correctly.
> Icosphere: Fix UV coordinate generation and texture seams

- pom.xml
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/utils/Remotery.kt
- src/test/tests/graphics/scenery/tests/unit/utils/RemoteryTests.kt
This PR adds support for the [Remotery](https://github.com/Celtoys/Remotery) profiler.
> Remotery support

- src/main/kotlin/graphics/scenery/utils/H264Encoder.kt
> H264Encoder: Fail gracefully if errors are encountered during init

- pom.xml
- src/main/kotlin/graphics/scenery/controls/SwingMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/repl/REPL.kt
- src/main/kotlin/graphics/scenery/volumes/RAIVolume.kt
- src/main/kotlin/graphics/scenery/volumes/SceneryContext.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/kotlin/graphics/scenery/volumes/VolumeManager.kt
- src/main/resources/graphics/scenery/repl/startup.py
- src/test/tests/graphics/scenery/tests/examples/stresstests/ExampleRunner.kt
- src/test/tests/graphics/scenery/tests/examples/volumes/FlybrainOutOfCoreExample.kt
- src/test/tests/graphics/scenery/tests/examples/volumes/OutOfCoreRAIExample.kt
This PR bumps the scijava parent POM to 29.0.0-beta-1, and changes the default REPL language to Python.
> Bump to scijava pom 29.0.0 beta1

- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/numerics/Random.kt
- src/main/kotlin/graphics/scenery/repl/REPL.kt
- src/main/resources/graphics/scenery/repl/startup.py
- src/test/tests/graphics/scenery/tests/unit/repl/REPLTests.kt
This PR adds unit tests for the REPL and enables its headless usage.
> Add tests for REPL and enable headless usage

- pom.xml
- src/main/kotlin/graphics/scenery/Camera.kt
- src/main/kotlin/graphics/scenery/DisableFrustumCulling.kt
- src/main/kotlin/graphics/scenery/InfinitePlane.kt
- src/main/kotlin/graphics/scenery/TextBoard.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/resources/graphics/scenery/backends/shaders/InfiniteGrid.frag
- src/main/resources/graphics/scenery/backends/shaders/InfiniteGrid.vert
Adds an InfinitePlane node to use as floor.
> Infinite plane

- src/main/kotlin/graphics/scenery/backends/RenderConfigReader.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/HeadlessSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/OpenGLSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/Swapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanCommandBuffer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanDevice.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanFramebuffer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanPipeline.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanShaderModule.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanTexture.kt
- src/main/kotlin/graphics/scenery/volumes/BufferSource.kt
- src/main/kotlin/graphics/scenery/volumes/BufferedVolume.kt
- src/main/kotlin/graphics/scenery/volumes/RAIVolume.kt
- src/main/kotlin/graphics/scenery/volumes/SceneryContext.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/kotlin/graphics/scenery/volumes/VolumeManager.kt
- src/main/resources/graphics/scenery/backends/DeferredShading.yml
- src/main/resources/graphics/scenery/backends/DeferredShadingStereo.yml
- src/main/resources/graphics/scenery/backends/shaders/DefaultDeferredInstanced.vert
- src/test/tests/graphics/scenery/tests/examples/advanced/ARExample.kt
- src/test/tests/graphics/scenery/tests/examples/volumes/BDVExample.kt
- src/test/tests/graphics/scenery/tests/examples/volumes/BigAndSmallVolumeExample.kt
- src/test/tests/graphics/scenery/tests/examples/volumes/ProceduralVolumeExample.kt
- src/test/tests/graphics/scenery/tests/examples/volumes/VolumeSamplingExample.kt
This PR fixes an issue that caused screen tearing and flickering because of a missing GPU-CPU sync on swapchain presentation.
> Fix Vulkan swapchain synchronisation issue

- src/main/kotlin/graphics/scenery/BoundingGrid.kt
- src/main/resources/graphics/scenery/volumes/BDVVolume.frag
- src/main/resources/graphics/scenery/volumes/BDVVolume.vert
Make bounding boxes visible again by writing correct depth values in fragment shader.
> BoundingGrid/Volume: Fix bounding box visibility

- src/main/kotlin/graphics/scenery/controls/behaviours/ArcballCameraControl.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/FPSCameraControl.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/MovementCommand.kt
Hi,
this is the best of #323 and `better-arcball` branch... *please review* (I'm a bit in hurry),
..and is based on top of the current `master`.
V.
> Pc camera controls addon take two

- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanBuffer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanTexture.kt
- src/main/kotlin/graphics/scenery/volumes/BufferedVolume.kt
- src/main/kotlin/graphics/scenery/volumes/SceneryContext.kt
- src/main/kotlin/graphics/scenery/volumes/SceneryStackManager.kt
- src/main/kotlin/graphics/scenery/volumes/VolumeManager.kt
- src/test/tests/graphics/scenery/tests/examples/volumes/ProceduralVolumeExample.kt
This PR optimises how volume updates are uploaded to the GPU.
> Volume transfer optimisations

- README.md
Adds the GTX 1650 Max-Q to the GPU compatibility table
> Add GTX 1650 Max-Q to README.md

- src/main/kotlin/graphics/scenery/Curve.kt
- src/main/kotlin/graphics/scenery/DummySpline.kt
- src/main/kotlin/graphics/scenery/Helix.kt
- src/main/kotlin/graphics/scenery/Rainbow.kt
- src/main/kotlin/graphics/scenery/RibbonDiagram.kt
- src/test/kotlin/graphics/scenery/tests/examples/advanced/RibbonRainbowExample.kt
- src/test/kotlin/graphics/scenery/tests/unit/RainbowTests.kt
The ribbons should also be displayable with a rainbow colour map
> Ribbon rainbow

- src/main/kotlin/graphics/scenery/CreateCommand.kt
- src/main/kotlin/graphics/scenery/MeshAdder.kt
- src/main/kotlin/graphics/scenery/Ruler.kt
- src/test/kotlin/graphics/scenery/tests/examples/basic/CreationExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/basic/DistanceMeasurement.kt
- src/test/kotlin/graphics/scenery/tests/examples/basic/MeshAddingExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/basic/RulerExample.kt
Here is the ruler stuff for scenery.
> Ruler stuff

- src/test/kotlin/graphics/scenery/tests/unit/RibbonDiagramTests.kt
RibbonDiagramTests: removed problematic protein
> RibbonDiagramTests: removed problematic protein

- src/test/kotlin/graphics/scenery/tests/unit/RibbonDiagramTests.kt
This should have been just a commit- I thought it would be more work to do.
> Reduced numbers of proteins to be tested to 19

- src/main/kotlin/graphics/scenery/Axis.kt
- src/main/kotlin/graphics/scenery/CatmullRomSpline.kt
- src/main/kotlin/graphics/scenery/Curve.kt
- src/main/kotlin/graphics/scenery/Protein.kt
- src/main/kotlin/graphics/scenery/UniformBSpline.kt
> Changed println to logger.info

- src/main/kotlin/graphics/scenery/VolumeMeasurer.kt
- src/test/kotlin/graphics/scenery/tests/unit/VolumeMeasuererTests.kt
Native support for volume measuring (of meshes!) for scenery.
> Volume measurement

- src/main/kotlin/graphics/scenery/volumes/Colormap.kt
- src/test/kotlin/graphics/scenery/tests/unit/volumes/ColormapTests.kt
This adds a simple method for creating a `Colormap` based on a single color. It linearly blends between black and the color, which is not completely natural, but useful. Happy for ideas for improvements!
> Colormap: add fromColor method

- src/main/kotlin/graphics/scenery/BoundingGrid.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLObjectState.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanTexture.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
This PR fixes issues SonarCloud has complained about.
> Sonarcloud bug fixes

- build.gradle.kts
- src/main/kotlin/graphics/scenery/Protein.kt
- src/test/kotlin/graphics/scenery/tests/examples/advanced/RainbowRibbonExample.kt
Added a catch for NullPointerException and updated BioJava. The latter seems to solve the issue, though we can't be certain since the error was occurring nondeterministically.
I was thinking about changing the error message to: "NullPointerException in the BioJava-Code occurred. Please update BioJava and see if this resolves the issue. If not, please contact burger@mpi-cbg.de" What do you think @skalarproduktraum ?
> BioJava NullpointerException

- build.gradle.kts
- src/main/kotlin/graphics/scenery/Mesh.kt
- src/main/kotlin/graphics/scenery/Settings.kt
- src/main/kotlin/graphics/scenery/backends/Shaders.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderModule.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/compute/EdgeBundler.kt
- src/main/kotlin/graphics/scenery/controls/GLFWMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/controls/JOGLMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
- src/main/kotlin/graphics/scenery/controls/ScreenConfig.kt
- src/main/kotlin/graphics/scenery/utils/ExtractsNatives.kt
- src/main/kotlin/graphics/scenery/utils/H264Encoder.kt
- src/main/kotlin/graphics/scenery/utils/Image.kt
- src/main/kotlin/graphics/scenery/utils/LogbackUtils.kt
- src/test/kotlin/graphics/scenery/tests/examples/basic/ReaderExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/VolumeSamplingExample.kt
This PR bumps Kotlin to 1.5.0, spirvcrossj to 0.8.0-1.1.106.0, and kot…linx-coroutines to 1.5.0.
> Gradle: Bump Kotlin to 1.5.0

- .gitlab-ci.yml
- build.gradle.kts
- src/test/kotlin/graphics/scenery/tests/unit/controls/OpenVRHMDTests.kt
This PR bumps: 
* bumps Kotlin to 1.6.0
* bumps lwjgl to 3.3.0
* bumps kotlinx-coroutines to 1.5.2
> Kotlin to 1.6.0 & lwjgl to 3.3.0

- src/main/kotlin/graphics/scenery/atomicsimulations/AtomicSimulation.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/OpenGLSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanDevice.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanScenePass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanTexture.kt
- src/main/kotlin/graphics/scenery/controls/Hololens.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
- src/main/kotlin/graphics/scenery/proteins/Protein.kt
- src/test/kotlin/graphics/scenery/tests/examples/basic/TexturedCubeExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/cluster/ProteinComparisonExample.kt
This PR cleans up the serious issues reported by SonarQube and changes a few deprecated functions, such as `toLowerCase()` and `callocStack()` to their newer cousins.
> (Partially) clean up reported SonarQube issues

- src/main/kotlin/graphics/scenery/controls/behaviours/VRSelectionWheel.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/VRTreeSelectionWheel.kt
- src/test/kotlin/graphics/scenery/tests/examples/advanced/VRControllerExample.kt
Make action list better accessible for change. To fit what I am going to tell in my presentation,
> VR*SelectionWheel.kt: Make action list better accessible for change

- src/main/kotlin/graphics/scenery/backends/ShaderCompiler.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanNodeHelpers.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanPipeline.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanScenePass.kt
- src/test/kotlin/graphics/scenery/tests/unit/backends/ShaderIntrospectionTests.kt
This PR improves various behaviour and coding style in the Vulkan renderer, see individual commits for details
> Various Vulkan cleanup and refactoring

- src/main/kotlin/graphics/scenery/backends/Display.kt
- src/main/kotlin/graphics/scenery/controls/Hololens.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
- src/main/kotlin/graphics/scenery/controls/TrackedStereoGlasses.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/Enablable.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/Enableable.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/VRGrab.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/VRPress.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/VRScale.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/VRSelect.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/VRSelectionWheel.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/VRTouch.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/VRTreeSelectionWheel.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/VRTwoHandDragBehavior.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/WheelAction.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/WheelEntry.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/WheelMenu.kt
- src/main/kotlin/graphics/scenery/primitives/LineBetweenNodes.kt
- src/test/kotlin/graphics/scenery/tests/examples/advanced/VRControllerExample.kt
Various small improvements in the VR UI I did for my project that might also help other users of scenery.
> VR UI improvements 

- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/net/Agent.kt
- src/main/kotlin/graphics/scenery/net/NodePublisher.kt
- src/main/kotlin/graphics/scenery/net/NodeSubscriber.kt
- src/test/kotlin/graphics/scenery/tests/unit/network/NodePublisherNodeSubscriberTest.kt
- src/test/kotlin/graphics/scenery/tests/unit/network/NodePublisherTest.kt
- src/test/kotlin/graphics/scenery/tests/unit/network/NodeSubscriberTest.kt
…n up teardown -> no more exceptions thrown in the tests
> trying to stop unstopping network tests by removing all exceptions thrown

- src/main/kotlin/graphics/scenery/volumes/Volume.kt
This PR enables parallel file reading in Volume. In the fromPath() routine, parallel reading of scifio's Plane objects is enabled  using Kotlin coroutines. For each worker thread, one ReaderFilter is created. For NIFTi files, e.g, the reading time is cut down to 20-25% of the original time.
The parallel reading behaviour can be disabled by setting the scenery setting `Volume.ParallelReads` to `false`, either by defining that setting programmatically, or by setting a system property, e.g. as command line option, `-Dscenery.Volume.ParallelReads=false`.
> Volume: Parallel file reading

- src/main/kotlin/graphics/scenery/geometry/Curve.kt
Contains the normal calculation for the curve covers as well as size allocations for the ArrayList in the general normal calculation for the curve.
> Normal calculation for curve covers

- src/main/kotlin/graphics/scenery/geometry/Curve.kt
- src/test/kotlin/graphics/scenery/tests/unit/RibbonDiagramTests.kt
This PR optimises the memory use of `Curve` by optimising out unnecessary list reallocations caused by `drop()`, `windowed()`, etc.
> Curve: memory optimisation

- src/main/kotlin/graphics/scenery/geometry/Curve.kt
This pull request removes superfluous instances of `ArrayList` in the `Curve` class for memory improvement purposes.
The memory performance is not yet stellar in this PR. However, here, the `LazyLogger()` is still active which took the lion's share of the unnecessary memory usage.
> Ribbon List to Buffer substitution

- .github/workflows/build.yml
Do not build all topic branches.
> CI: build only mainline and PRs

- src/main/kotlin/graphics/scenery/Icosphere.kt
- src/main/kotlin/graphics/scenery/Sphere.kt
Creates flipped normals when `insideNormals = true` is passed to the constructor, the same way it works as with the Box class.
> adds insideNormals for Sphere

- src/main/kotlin/graphics/scenery/controls/InputHandler.kt
fixes https://github.com/scenerygraphics/sciview/issues/477
Thanks Curtis!
> InputHandler: fixing key bindings editor

- src/main/kotlin/graphics/scenery/DefaultNode.kt
- src/main/kotlin/graphics/scenery/Node.kt
Closes https://github.com/scenerygraphics/scenery/issues/552
> Node, DefaultNode: runRecursive on copy of children array

- README.md
- build.gradle.kts
- gradle.properties
- settings.gradle.kts
- src/main/kotlin/graphics/scenery/backends/vulkan/SwingSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
This PR prepares the repo for the 0.9.0 release.
* bumps version to 0.9.0
* includes fix for black screen issue on macOS
The staging repo for the release is already available at https://oss.sonatype.org/content/repositories/graphicsscenery-1221 (URL subject to change as new release uploads happen)
> 0.9.0 release preparations

- src/test/kotlin/graphics/scenery/tests/examples/advanced/VRControllerAdvancedExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/advanced/VRControllerExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/stresstests/ExampleRunner.kt
revive simple VRController example and clean up and extend documentation on both examples
relates to #514
> Improve vr examples

- src/main/kotlin/graphics/scenery/OrientedBoundingBox.kt
code provided by @skalarproduktraum
> OrientedBoundingBox.kt: fix scaled intersection 

- .gitlab-ci.yml
- buildSrc/src/main/kotlin/scenery/base.gradle.kts
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
This PR updates Gitlab CI with a new Docker image, containing an updated Vulkan SDK (1.3.261.1), together with node.js 16 to support the latest Argos versions. New version of #624.
> CI: Update Argos and Vulkan SDK

- .github/workflows/build.yml
- .gitlab-ci.yml
- build.gradle.kts
- buildSrc/src/main/kotlin/scenery/base.gradle.kts
as discussed here https://imagesc.zulipchat.com/#narrow/stream/327495-scenery.2Bsciview/topic/CI.20log.20readability.3A.20split.20build.20and.20test
> CI: split build task into build and test for better log readability

- src/main/kotlin/graphics/scenery/controls/MouseAndKeyHandlerBase.kt
- src/main/kotlin/graphics/scenery/utils/ExtractsNatives.kt
This PR improves loading the native libraries required for JInput. It now uses default Java classpath file access, instead of the obsolete method of trying to find the native JAR from the classpath and extracting it.
In addition, this also should fix the spurious warnings about the JInput native JAR not being found.
> Improve JInput native loading

- build.gradle.kts
- src/main/kotlin/graphics/scenery/volumes/VolumeManager.kt
Update BVV to match https://github.com/bigdataviewer/bigvolumeviewer-core/pull/18
> Update BVV to 0.3.3

- README.md
- settings.gradle.kts
> Build: Bump version to 0.9.1

- README.md
- settings.gradle.kts
> Build: Bump version to 0.9.2

- gradle/wrapper/gradle-wrapper.properties
- gradlew.bat
> Build: Bump Gradle to 8.7

- src/main/kotlin/graphics/scenery/volumes/ColormapPanel.kt
- src/main/kotlin/graphics/scenery/volumes/TransferFunctionEditor.kt
Fixes https://github.com/scenerygraphics/scenery/issues/715
> Use absolute resource paths for gear icon

- src/main/kotlin/graphics/scenery/controls/behaviours/ConfirmableClickBehaviour.kt
- src/main/kotlin/graphics/scenery/controls/eyetracking/PupilEyeTracker.kt
This adds a ClickBehaviour derivate that needs to be triggered twice to perform an action.
> Add ConfirmableClickBehaviour

- src/main/kotlin/graphics/scenery/Origin.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
This PR introduces a new option for setting custom origins of Volumes. Supercedes #731.
> Origin/Volume: Introduce support for custom origins and use in Volume

- src/main/kotlin/graphics/scenery/volumes/SceneryContext.kt
This PR:
* fixes an issue where the volume rendering would flicker whenever the BVV LUT was updated, which is quite annoying
* this fix double-buffers the LUT and waits for it to become available on the GPU before replacing the old one, fixing the flickering issue
> SceneryContext: Fix flickering issue when BVV LUTs update

- src/main/kotlin/graphics/scenery/net/Agent.kt
- src/main/kotlin/graphics/scenery/net/NodePublisher.kt
- src/main/kotlin/graphics/scenery/net/NodeSubscriber.kt
- src/test/kotlin/graphics/scenery/tests/unit/network/NodePublisherNodeSubscriberTest.kt
hopefully fix flaky tests, muted some caught exceptions, documentation
> Fix , NodePublisherNodeSubscriberTest
