scenerygraphics/scenery

- .travis.yml
We fixed the OSX build recently, so it's not allowed to fail anymore.
> Removed Allowed Failure on OSX

- src/main/kotlin/scenery/SceneryDefaultApplication.kt
- src/test/kotlin/scenery/tests/examples/BloodCellsExample.kt
- src/test/kotlin/scenery/tests/examples/BoxedProteinExample.kt
- src/test/kotlin/scenery/tests/examples/CubeExample.kt
- src/test/kotlin/scenery/tests/examples/LineExample.kt
- src/test/kotlin/scenery/tests/examples/MultiBoxExample.kt
- src/test/kotlin/scenery/tests/examples/MultiBoxInstancedExample.kt
- src/test/kotlin/scenery/tests/examples/OpenVRExample.kt
- src/test/kotlin/scenery/tests/examples/SponzaExample.kt
- src/test/kotlin/scenery/tests/examples/TexturedCubeExample.kt
- src/test/kotlin/scenery/tests/examples/VertexUpdateExample.kt
This PR moves scenery's examples over to use the new SceneryDefaultApplication class, reducing the boilerplate code needed from setup, so the actual example code is highlighted more.
> Move to SceneryDefaultApplication

- .travis.yml
- README.md
- build.gradle
- src/main/kotlin/scenery/GenericTexture.kt
- src/main/kotlin/scenery/rendermodules/opengl/DeferredLightingRenderer.kt
* ClearGL is at 2.0.0-SNAPSHOT now, after merging the scenegraph branch
* This updates README and build files
* adjustments to GenericTexture and DeferredLightingRenderer such that the texture data
types do not depend on CoreMem
> Moving to ClearGL 2.0.0 now

- src/main/kotlin/graphics/scenery/Camera.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/ArcballCameraControl.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/FPSCameraControl.kt
* fixes transition from ArcballCameraControl to FPSCameraControl and vice versa
* fixes issue where camera target/position might be accidentally overwritten by ArcballCameraControl
* removes yaw/pitch from accessible state in {Arcball,FPS}CameraControl, as cam.rotation should be the only persistent state kept
> Camera control fixes

- src/main/resources/graphics/scenery/backends/DeferredShading.yml
- src/main/resources/graphics/scenery/backends/vulkan/shaders/DefaultDeferred.frag
- src/main/resources/graphics/scenery/backends/vulkan/shaders/DeferredLighting.frag
This version contains implementation of Alchemmy SSAO algorithm, and compression of Normal Vectors using Octahedron and Spherical unit vectors, for the Vulkan Renderer. The usage of z component in the SSAO algorithm as Bias Scale needs to be verified and corrected.
> Normal compression and alchemy ssao

- src/main/kotlin/graphics/scenery/HasGeometry.kt
This PR solves #8 and introduces a more efficient OBJ loading, which is especially faster on smaller meshes.
No actual statistics, just examples.
* Powerplant: 97854.898825 ms
* Rungholt: 50352.615261 ms
* Sponza: 2272.888937 ms
* Powerplant: 55771ms
* Rungholt: 27734ms
* Sponza: 1593ms
* Powerplant: 67706ms
* Rungholt: 32548ms
* Sponza: 1200ms
* Powerplant: 73000ms
* Rungholt: 33260ms
* Sponza: (Crashes)
> OBJ loader optimization

- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanObjectState.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanUBO.kt
* command buffers are now invalidated for the right render pass
* command buffer metadata has been moved from VulkanRenderer to
VulkanRenderpass
* VulkanObjectState no longer stores references to command buffers
> Fixes for command buffer caching

- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/utils/SceneryPanel.kt
The renderer should not modify properties of the scenery panel, thus remove all calls to `panel.{pref,min}{Width,Height}` in `OpenGLRenderer.kt`. Still, the minimum width and height need to be larger than zero to avoid zero length rendering buffers. This is handled in the `SceneryPanel` constructor.
> Do not set prefWidth/Height in renderer

- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderModule.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanShaderModule.kt
This PR introduces a simple caching mechanism for shaders, such that they are only compiled once, when they are encountered. Works with both OpenGLRenderer and VulkanRenderer.
> Introduce caching of already-compiled shader modules

- src/main/kotlin/graphics/scenery/Hub.kt
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/SceneryElement.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
This adds a shutdown hook to `SceneryBase`, in the form of the `close()` method. It also adds the `Application` type to Hub, such that the application object can be made available in the hub and accessed (and closed, for that matter).
The PR also introduces a small fix in OpenGLRenderer which should handle closing JOGL windows more gracefully.
> Add shutdown hook to SceneryBase

- src/main/kotlin/graphics/scenery/backends/RenderConfigReader.kt
- src/main/kotlin/graphics/scenery/backends/UBO.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanFramebuffer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/resources/graphics/scenery/backends/DeferredShading.yml
- src/main/resources/graphics/scenery/backends/DeferredShadingStereo.yml
* introduces customizable framebuffer attachment sizes, such that e.g. AO can be done at a lower resolution
* simplifies the framebuffer attachment definition in the render config YAML files
* `VulkanRenderer`: Fixes an issue where stale command buffers would not be re-recorded in stereo mode
* `VulkanFramebuffer`: Refactoring to remove redundant code
> Custom attachment sizes

- src/main/kotlin/graphics/scenery/Settings.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
Fixes an issue where rendering was incorrect when using sub- or supersampling (as is automatically done on macOS when running on a Retina display).
> Fix supersampling

- README.md
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
Changes LightParameters and VRParameters to be regular uniform buffers without dynamic offsets. This lowers the number of dynamic uniform buffers required in the pipeline and causes less issues on some AMD cards.
> VulkanRenderer: Descriptor set improvements

- src/main/kotlin/graphics/scenery/utils/SceneryPanel.kt
This PR corrects image flipping when rendering to a JavaFX SceneryPanel. OpenGL Y orientation was wrong before.
> Correct image flipping when rendering to a JavaFX SceneryPanel

- src/main/kotlin/graphics/scenery/backends/vulkan/FXSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/HeadlessSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/OpenGLSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/Swapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/test/tests/graphics/scenery/tests/examples/stresstests/RunAllExamples.kt
This PR removes all window surfaces from HeadlessSwapchain and FXSwapchain, potentially resulting in less issues when running in conjunction with JavaFX. FXSwapchain now inherits from HeadlessSwapchain, making their hierarchy more clear.
The changes also decrease the bandwidth usage of JavaFX windows substantially.
> Headless Vulkan without surfaces

- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/UBO.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLUBO.kt
This PR introduces dynamic resizing of OpenGL buffers, should they exceed their current size.
It also fixes a performance issue when running JavaFX (see scenerygraphics/SciView#99), and fixes a problem with push mode in OpenGL, where the scene would be marked update while it is not.
> OpenGL dynamic buffer resizing, high CPU use fix & push mode fixes

- src/main/kotlin/graphics/scenery/SceneryBase.kt
This is necessary when inheriting from SceneryBase *and* overriding the
main() method. All of these are necessary inside any overriding main()
method.
> Make accumulator, currentTime, t, and shouldClose protected

- pom.xml
Hi @skalarproduktraum 
in order to integrate SciView / Scenery with Clearcontrol, I'm suggesting upgrading scenerys CoreMem version. I don't see any side effects but I'm also new to Scenery. Please check/test carefully before merging ;-)
Also: I'm just highlighting that groupId and artifactId of coremem changed. That might make things complicated as coremem.CoreMem and net.clearcontrol.coremem can coexist in one project. However both bring the same classes. Thus, further cleaning up the dependency tree might be necessary.
Thanks!
Cheers,
Robert
> upgrade coremem dependency

- pom.xml
- src/main/kotlin/graphics/scenery/backends/ShaderPackage.kt
- src/main/kotlin/graphics/scenery/backends/Shaders.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderModule.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanShaderModule.kt
This PR upgrades spirvcrossj to 1.1.106.0 and makes the necessary changes to Shaders, ShaderPackage, OpenGLShaderModule, and VulkanShaderModule required by changes in SPIRV-cross.
> Upgrade spirvcrossj 1.1.106.0

- pom.xml
Starting with pom-scijava-base 7.0.0, some native-related properties are now defined automatically. See:
https://github.com/scijava/pom-scijava-base/commit/42759cc96b81bb0cdd2bb5e1fa23567c77962f2e
The pom-scijava 27 series extends a new-enough pom-scijava-base to inherit these properties. So we can reuse them here without needing to define our own explicit profiles anymore.
> Simplify native profiles

- pom.xml
- src/main/kotlin/graphics/scenery/backends/vulkan/VU.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanDevice.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanObjectState.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
In VulkanRenderer, the presentation command buffer was waited for right after submission, creating GPU bubbles, because of unnecessary sync. With this PR, the presentation command buffer is only waited for right before re-recording, improving GPU utilisation (values from a GTX 1080Ti, taken over 100s after warmup, utilisation via NvAPI):
Test case | Frame Rate | GPU utilisation
----------|------------|--------
SponzaExample 720p (before) | 217-321fps | 44-62%
SponzaExample 4k (before) | 75-100fps | 74-86%
SponzaExample 4k stereo (before) | 80-108fps | 72-85%
| | 
SponzaExample 720p | 354-434fps | 46-81%
SponzaExample 4k | 102-153fps | 76-96%
SponzaExample 4k stereo | 108-174 fps | 93-98%
In addition, this PR fixes two cases of API abuse:
* in VU and VulkanObjectState, `descriptorCount` is …
> VulkanRenderer: Bubble fixes

- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
This PR fixes:
* Volume: Texture would be repeated in Z direction, instead of being clamped
* OpenGLRenderer: Does not heed depth test mode specified in `Material.depthTest`
> Volume repeat fix

- src/main/kotlin/graphics/scenery/Material.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanObjectState.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
This PR introduces wireframe rendering, to be activated via `Material.wireframe`. It addresses #128.
> Wireframe rendering

- pom.xml
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/MultiBoxInstancedExample.kt
- src/test/tests/graphics/scenery/tests/examples/basic/TexturedCubeExample.kt
- src/test/tests/graphics/scenery/tests/examples/stresstests/ExampleRunner.kt
This PR addresses an issue where OpenGL would throw exceptions on quit. It also bumps ClearGL to 2.2.7 and allows manual specification of the renderers to use for the ExampleRunner.
> OpenGL window handling improvements

- src/main/kotlin/graphics/scenery/Camera.kt
- src/main/kotlin/graphics/scenery/Scene.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/SelectCommand.kt
- src/test/tests/graphics/scenery/tests/examples/advanced/PickerExample.kt
- src/test/tests/graphics/scenery/tests/unit/SceneTests.kt
This PR includes world direction and world position of the initial ray into RaycastResult and extends SelectCommand to also hand over the click x/y to the function called on the matched object(s).
> Include metadata in RaycastResult

- pom.xml
This updates Scenery's dependencies to include native artifacts for the following platforms only: linux32, linux64, macosx, windows64. The dependency footprint is reduced from 347M to 242M (a reduction of 105M or ~30%).
Here is a diff of the dependency tree:
```diff
diff --git a/before b/after
index e55219d3..10f8244a 100644
--- a/before
+++ b/after
@@ -13,37 +13,37 @@
[INFO] +- org.jetbrains.kotlin:kotlin-reflect:jar:1.3.50:compile
[INFO] +- org.jetbrains.kotlinx:kotlinx-coroutines-core:jar:1.3.1:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.50:compile
-[INFO] +- org.jogamp.gluegen:gluegen-rt-main:jar:2.3.2:compile
-[INFO] |  +- org.jogamp.gluegen:gluegen-rt:jar:2.3.2:compile
-[INFO] |  +- org.jogamp.gluegen:gluegen-rt:jar:natives-android-aarch64:2.3.2:compile …
```
> Depend on native artifacts of supported platforms only

- src/main/kotlin/graphics/scenery/Camera.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
- src/test/tests/graphics/scenery/tests/unit/CameraTests.kt
This PR makes a Camera's children adhere to the same transform properties as other nodes, such that objects can be more easily attached to cameras, and will follow it's position and rotatation.
(Somewhat related to #272)
> Camera transform fix

- pom.xml
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/backends/Renderer.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/controls/GLFWMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/controls/InputHandler.kt
- src/main/kotlin/graphics/scenery/controls/MouseAndKeyHandlerBase.kt
- src/main/kotlin/graphics/scenery/net/NodePublisher.kt
- src/main/kotlin/graphics/scenery/net/NodeSubscriber.kt
- src/main/kotlin/graphics/scenery/utils/Statistics.kt
- src/test/tests/graphics/scenery/tests/examples/basic/SwingTexturedCubeExample.kt
This PR fixes cleanup and threads not closing in NodePublisher, NodeSubscriber, Statistics, and MouseAndKeyHandlerBase. It also replaces FPSAnimator with Animator in OpenGLRenderer for improved shutdown handling, and cleans up the shutdown code in OpenGLRenderer.
> Fix cleanup code

- src/main/kotlin/graphics/scenery/backends/RenderConfigReader.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanBuffer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanBufferPool.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanDevice.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanFramebuffer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanObjectState.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanTexture.kt
This PR improves layout transitions between render passes, making the Vulkan renderer work correctly on Icy Lake's Iris Plus GPUs (see #287). It also improves cleanup code such that no objects are left deallocated on exit (which should get cleaned up by the driver anyway, though).
> Vulkan transitions and cleanup

- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/controls/GLFWMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/controls/InputHandler.kt
- src/main/kotlin/graphics/scenery/controls/JOGLMouseAndKeyHandler.kt
- src/main/kotlin/graphics/scenery/controls/MouseAndKeyHandlerBase.kt
- src/main/kotlin/graphics/scenery/controls/SwingMouseAndKeyHandler.kt
This PR fixes issues with HiDPI rendering on Windows and OSX (Linux untested so far).
> Swing HiDPI fixes

- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/OrientedBoundingBox.kt
- src/test/tests/graphics/scenery/tests/unit/NodeTests.kt
The position of the children is defined w.r.t. the parent and must be used as an offset when finding the maximum bounding box.
> Fix maximum bounding box for Nodes with children

- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanObjectState.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderpass.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanShaderModule.kt
- src/main/kotlin/graphics/scenery/volumes/VolumeShaderFactory.kt
- src/test/tests/graphics/scenery/tests/examples/stresstests/ExampleRunner.kt
This PR extends the handling of descriptor sets in such a way that multiple samplers can be contained in a single descriptor set, preventing the problem of descriptor set exhaustion on less tolerant/capable GPUs (e.g. Intel integrated ones).
It also introduces a per-test runtime limit for the ExampleRunner which can be adjusted by setting the system property `scenery.ExampleRunner.maxRuntimePerTest` to a amount of desired minutes. Default is 5 minutes.
> Vulkan texture descriptor set improvements

- pom.xml
* remove all version tags for artifacts managed by `pom-scijava`
* remove hard-coded version pinning for `n5` artifacts
* override `jacoco-maven-plugin.version` property instead of hard-coding the version
* remove redundant `scijava.jvm.version` specified in parent POM
> POM: remove redundant version tags

- pom.xml
- src/main/kotlin/graphics/scenery/controls/InputHandler.kt
here's a couple of things I would really use to have for SciView:
- the `InputHandler.openKeybindingsGuiEditor()` that opens (also in scenery, in theory) the key bindings GUI editor
- the `getAllBehaviours()` listing/overview method and `getKeyBindings()` query method
- also `removeKeyBinding()` (and any binding updating method in `INputHandler`) are maintaining the synchronization of ui-behaviours `InputTriggerMapping` and `InputTriggerConfig` explicitly and on its own (....and are now functional)
- these items need the PRs from ui-behaviour... this PR will not compile without it
Plus, I noticed overlapping key bindings:
- gamepad_cam_control was using 'P' just like screenshots, I remapped that to 'G' (for *G*amepad)
- but 'G' was used for mouse_control, so I remapped it to 'M' (for …
> inputHandler add ons

- src/main/kotlin/graphics/scenery/controls/MouseAndKeyHandlerBase.kt
- src/main/kotlin/graphics/scenery/utils/ExtractsNatives.kt
This PR fixes the loading of native libraries for JInput on macOS: By creating a copy of the `.jnilib` file as `.dylib` it'll make the library conform to the current JVM naming conventions.
> Fix macOS JInput native loading

- src/main/kotlin/graphics/scenery/InfinitePlane.kt
- src/main/kotlin/graphics/scenery/RenderingOrder.kt
- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/resources/graphics/scenery/backends/shaders/InfiniteGrid.frag
- src/main/resources/graphics/scenery/volumes/BDVVolume.frag
Introduces RenderingOrder interface in order to correctly render transparent objects and floors etc.
Fixes second part of https://github.com/scenerygraphics/sciview/issues/301
> Rendering order

- src/main/kotlin/graphics/scenery/Axis.kt
- src/main/kotlin/graphics/scenery/RibbonDiagram.kt
- src/test/kotlin/graphics/scenery/tests/examples/advanced/RibbonRainbowExample.kt
Positions the ribbon to the origin by default. Might be useful for the workshop as sometimes coordinates in PDBs are, for whatever reason, translated to somewhere on mars. Now our users will see the protein in front of them
> Ribbon position

- build.gradle.kts
parsing a short version of the git commit hash and then save it in the manifest
This is vital for the `MeshDemo` of sciview
> add git commit hash attribute in manifest

- buildSrc/src/main/kotlin/scenery/base.gradle.kts
This PR adds back a `./gradlew run` task that can be used to start single scenery examples. Thanks @elect86!
> Add run tasks for gradle

- build.gradle.kts
This PR bumps spirvcrossj to the latest version, 0.7.1-1.1.106.0, solving some classloader issues reported by @elect86 and @ljjh20.
> Gradle: Bump spirvcrossj to 0.7.1-1.1.106.0

- build.gradle.kts
- gradle.properties
This PR fixes the BigVolumeViewer version in the Gradle build to the correct jitpack one, and removes the reference to release version 0.1.8. This can be changed back after tpietzsch/jogl-minimal#14 is merged.
> Fix BigVolumeViewer version in Gradle build

- buildSrc/src/main/kotlin/scenery/base.gradle.kts
This PR:
* adds `SCENERY_JVM_ARGS` env var to be passed on to the JVM running the example in the `run` task
* checks if the Gradle property `example` is set, and leaves out any config if it is not, such that the build is not compromised.
> Gradle: `run` task additions

- build.gradle.kts
- buildSrc/src/main/kotlin/scenery/base.gradle.kts
This PR specifies native versions in Gradle explictly, to prevent creation of a broken POM, make BDV/BVV API dependencies in order to leak them to dependant projects.
Probably @elect86 will want to have a look at this, as I believe that can be fixed within his sciJava Gradle plugin 👍
> Gradle: Specify versions for natives explicitly 

- build.gradle.kts
This PR updates ffmpeg to 4.2.2-1.5.3 -- this is the same version nd4j uses, so this removes a version clash that should make @ljjh20 happy 👍
> Gradle: Update ffmpeg to 4.2.2-1.5.3

- src/main/kotlin/graphics/scenery/volumes/OrthoView.kt
This adds a JvmName to OrthoView so it can be referenced from Java and Python (via scyjava) easily.
> OrthoView.kt: add JvmName for OrthoView

- build.gradle.kts
This PR bumps spirvcrossj to 0.8.0-1.1.106.0 and adds the temporary staging repositories. If the build works, the new spirvcrossj version can be published on Sonatype.
> Build: Bump spirvcrossj to 0.8.0-1.1.106.0

- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/kotlin/graphics/scenery/volumes/VolumeManager.kt
- src/test/kotlin/graphics/scenery/tests/examples/compute/CustomVolumeManagerExample.kt
@aryaman-gupta had reported an issue where compute shaders would not be used if the VolumeManager is recreated. This PR fixes that, and introduces a new `customTextures` list in VolumeManager, where the developer can specify custom textures that are not under the VolumeManager's responsibility.
> VolumeManager/Volume: Fix issue with compute shaders

- build.gradle.kts
This PR disable the creation of the `module.json` file when building on Jitpack, as Jitpack performs opaque postprocessing on that file which leads to missing natives dependencies, and especially issues downstream with transitive dependencies.
> Jitpack: Don't create Gradle metadata JSON file

- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
This PR fixes #421, where screenshots were not overwritten as requested when using the Vulkan renderer.
> VulkanRenderer: Fix issue where screenshots would not be overwritten

- gradle/wrapper/gradle-wrapper.properties
This PR bumps the version of the Gradle wrapper to 7.1.1.
> Gradle: Bump Gradle version to 7.1.1

- build.gradle.kts
This PR adds the Gradle task `shadowJar` to package scenery and all of its dependencies in one fat JAR.
> Gradle: Add ability to create far JAR using shadowJar task

- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/utils/VideoEncoder.kt
This PR:
* renames H264Encoder to VideoEncoder,
* fixes RTP stream output to use the actually correct format such that it can be consumed e.g. by VLC
* reintroduces the creation of SDP files in case a network video stream via RTP is opened
> Fix RTP video streaming

- build.gradle.kts
This PR bumps Kotlin to 1.5.31, and brings back slf4j-simple as test dependency.
@frauzufall: slf4j-simple was removed as test dependency by you -- any particular reason for that?
> Gradle: Bump Kotlin to 1.5.31

- src/main/kotlin/graphics/scenery/Camera.kt
- src/main/kotlin/graphics/scenery/Scene.kt
- src/main/kotlin/graphics/scenery/controls/behaviours/MouseDragSphere.kt
- src/main/kotlin/graphics/scenery/volumes/OrthoView.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/OrthoViewExample.kt
- src/test/kotlin/graphics/scenery/tests/unit/SceneTests.kt
Depends on #406 and #411.
- Add node filter to raycast collision detection as second mode instead of ignoring classes.
- OrthoView Input behavior uses this new filtering.
- OrthoView input behavior now adds itself automatically.
> Orthoview improvements for volume visualisation

- build.gradle.kts
- src/main/kotlin/graphics/scenery/repl/REPL.kt
- src/test/kotlin/graphics/scenery/tests/examples/stresstests/ExampleRunner.kt
This PR
* bumps Kotlin to 1.6.10
* bumps dokka to 1.6.0
* bumps kotlinx-coroutines to 1.5.2-native-mt
* bumps slf4j-simple/slf4j to 1.7.32
* bumps JOCL to 2.0.4
* bumps scijava-common to 2.78.1
* bumps jackson to 2.13.0
* bumps jeromq to 0.5.2
* bumps kryo to 5.2.0
* bumps msgpack to 0.9.0
* bumps ffmpeg to 4.3.2-1.5.5
* bumps ClassGraph to 4.8.137
* removes Reflections
* creates the REPL directly with Python as language to improve startup time
> Dependency updates

- src/main/kotlin/graphics/scenery/Camera.kt
- src/main/kotlin/graphics/scenery/Scene.kt
- src/test/kotlin/graphics/scenery/tests/examples/advanced/MouseInputExample.kt
- src/test/kotlin/graphics/scenery/tests/unit/CameraTests.kt
This PR fixes #381. The skewness for creating world-space rays from screen-space positions was caused by an incorrect data type for calculating the aspect ratio, with `width/height` being used, and resulting in an integer, while `width.toFloat()/height.toFloat()` would have been correct. The screenPointToRay() method was also refactored for improved readability.
Thanks to @moreApi for the bug report!
> Correct screen point to ray conversion

- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanObjectState.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/kotlin/graphics/scenery/volumes/VolumeManager.kt
- src/main/resources/graphics/scenery/volumes/SampleBlockVolume.frag
- src/main/resources/graphics/scenery/volumes/SampleSimpleVolume.frag
Volume/Manager, Sample*Volume.frag: only consider used slicing planes in shader -> better performance
> Remove performance cost of unused slicing planes

- src/main/kotlin/graphics/scenery/backends/ShaderCompiler.kt
Changes spirv version scenery compiles shaders to from 1.5 to 1.2. Version 1.5 was too new for certain functionalities, like Vulkan debug printfs
> ShaderCompiler: changes spirv version from 1_5 to 1_2

- src/test/kotlin/graphics/scenery/tests/unit/RibbonDiagramTests.kt
This PR fixes an issue that occurs on Windows GitHub actions runners, where a lot of memory is requested (for no reason) that exceeds the runner's capabilities.
> RibbonDiagramTests: Fix memory exceeded CI issue

- build.gradle.kts
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/utils/ExtractsNatives.kt
This PR addresses a recently-introduced issue due to a file dependency on the JHDF5 fat jars for M1 support. The dependency has been removed and replaced with on-the-fly loading and caching of those libraries.
> Fix generated Maven POM/On-the-fly loading of M1 binaries for JHDF5

- .gitlab-ci.yml
- src/main/kotlin/graphics/scenery/volumes/RAIVolume.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/test/kotlin/graphics/scenery/tests/examples/stresstests/ExampleRunner.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/BDVExample.kt
This PR changes the factory methods of `Volume` to return volumes created from SpimData/BDV XML as RAIVolume instead of Volume, which makes more sense. Thanks to @RuoshanLan for the idea 👍
> Return Volumes created from SpimData/BDV XML as RAIVolume

- build.gradle.kts
As some dependencies of Biojava introduce POM issues, this PR propagates the exclusions we have in the Gradle build file also to the pom.xml that is create in the build process, so these are visible to dependents of scenery as well.
> Gradle: Propagate dependency exclusions on Biojava to POM as well

- .gitlab-ci.yml
- buildSrc/src/main/kotlin/scenery/base.gradle.kts
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanNodeHelpers.kt
- src/main/kotlin/graphics/scenery/utils/TimestampedConcurrentHashMap.kt
This PR addresses an issue where reassigned textures would not correctly clear the used/unused texture state. 
Thanks to @PowerOfNames for pointing out this issue 👍
> Fix issue where used/unused textures were cached incorrectly

- build.gradle.kts
This PR fixes a bug, where, due to a logic mistake in build.gradle.kts, the inclusion of the OpenVR binaries for Windows and Linux was omitted. Dependants were not affected, as the POM creation was handled separately.
Thanks @moreApi for the report!
> Fix missing OpenVR binaries

- .github/workflows/build.yml
- build.gradle.kts
- src/main/kotlin/graphics/scenery/volumes/VolumeManager.kt
This PR bumps BVV to the latest repository version, which includes a fix for #493. 
From #493:
Thanks to a nice Heisenbug hunting session with @tpietzsch, the culprits turned out to be the use of Matrix4f.unprojectInvRay() in combination with MipmapSizes.init(). The latter contains the assumption that the ray returned from unprojectInvRay() reaches from the near to the far plane. This was the case until JOML 1.9.17. In JOML 1.9.18, this changed, due to the support for far plane at infinity. This effectively removes a far/near division from the ray length, leading to a ray that doesn't touch the far plane.
In scenery, there are order-of-magnitude differences between near and far plane, while in BVV, they are of the same order. The issue did therefore not appear in BVV. As …
> Fix BigVolumeViewer resolution level loading

- src/main/kotlin/graphics/scenery/volumes/BufferedVolume.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
This PR fixes an issue where `Volume.currentTimepoint` always returned 0. It now returns the correct value, and sets the BVV state variable `numTimepoints` correctly as well.
cc @moreApi
> Volume: Let currentTimepoint return the correct value

- src/main/kotlin/graphics/scenery/volumes/TransferFunction.kt
Fixes a bug where the !stale return of TransferFunction.serialize() returns the buffer with the wrong Endianess.
> TransferFunction.serialize() fix endianess for stale return

- src/main/kotlin/graphics/scenery/volumes/RAIVolume.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/resources/graphics/scenery/repl/startup.py
- src/test/kotlin/graphics/scenery/tests/examples/volumes/ProceduralVolumeExample.kt
This PR unifies the composeModel() routines for all Volume subtypes. This should correct centering issues, as well as issues with bounding boxes.
cc @RuoshanLan @moreApi
> Volume: Unify composeModel() routines, remove RAIVolumeSpatial

- src/main/kotlin/graphics/scenery/attribute/spatial/DefaultSpatial.kt
This happens because in scenery's spatial.world also the model is included.
> DefaultSpatial: worldPosition with a null argument and a non scene parent now does not apply the position twice to the return value.

- .gitlab-ci.yml
This PR should stabilise Argos comparison results, by using the `scenery.RandomSeed` system property for seeding the PRNG.
> Gitlab CI: Stabilise Argos results by using scenery.RandomSeed property

- src/main/kotlin/graphics/scenery/geometry/Curve.kt
- src/main/kotlin/graphics/scenery/proteins/Helix.kt
The cover calculation for the curve class was erroneous, leaving the empty tubes open for the user to see. The error was tracked down to a confusion of `last()` with `first()` and will be fixed by this pull request.
Moreover, the calculation of the Curves was delegated to `recalculateNormals()`. From this pull request onwards, the calculation will happen in the `Curve` class itself.
> Fixed covers for curves and computed normals within the curve class

- src/main/kotlin/graphics/scenery/volumes/Volume.kt
This PR exposers scifio's metadata table as Volume.metadata entries when using Volume.fromPath(). Entries are copied such that references to scifio's objects are not required. As the copied objects are usually just string data, this should not incur any significant overhead.
> Volume: Expose scifio's metadata table 

- .gitlab-ci.yml
- src/main/kotlin/graphics/scenery/compute/OpenCLContext.kt
- src/main/kotlin/graphics/scenery/fonts/SDFFontAtlas.kt
- src/test/kotlin/graphics/scenery/tests/unit/fonts/SDFFontAtlasTests.kt
This PR skips OpenCL-related examples and tests on Docker due to a bug in Nvidia's Docker engine.
> Disable OpenCL-related examples and tests on Gitlab CI

- src/main/kotlin/graphics/scenery/primitives/Plane.kt
Fixing a bug where the planes origin z-part was offset by its sidelength instead of being at 0
> Plane-zOffset fix

- src/main/kotlin/graphics/scenery/backends/UBO.kt
This PR: 
* adds support for integer arrays in UBOs
* fixes an issue where `std140` array padding rules were not taken into account correctly
> Support for int arrays in UBOs

- build.gradle.kts
- buildSrc/src/main/kotlin/scenery/base.gradle.kts
- buildSrc/src/main/kotlin/scenery/publish.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- bump Shadow to 8.1.1
- minors DSLs constructs
- removed duplicated/unused code
> Bump Gradle to 8.0.2 plus minors

- src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
This PR deprecates the OpenGL renderer. 
It will be removed in the next release as the Vulkan renderer:
* is mature now 
* is supported on all platforms
* has already more features
* is more easily testable
The PR adds a deprecation warning on instancing of the OpenGLRenderer, and adds a `@Deprecated` annotation to the class.
> Deprecate OpenGL renderer

- src/main/kotlin/graphics/scenery/volumes/VolumeManager.kt
- src/main/resources/graphics/scenery/volumes/AccumulateBlockVolume.frag
- src/main/resources/graphics/scenery/volumes/AccumulateSimpleVolume.frag
VolumeManager, AccumulateBlockVolume.frag, AccumulateSimpleVolume.frag: Respect Volume visibilty of the volume node.
Add sceneGraphVisibility per volume shader uniform. Should solve https://github.com/scenerygraphics/sciview/issues/422
> Volume Scene Graph Visibility Fix

- build.gradle.kts
- src/main/kotlin/graphics/scenery/volumes/BufferedSimpleStack3D.kt
- src/main/kotlin/graphics/scenery/volumes/BufferedVolume.kt
- src/main/kotlin/graphics/scenery/volumes/RAIVolume.kt
- src/main/kotlin/graphics/scenery/volumes/SceneryContext.kt
- src/main/kotlin/graphics/scenery/volumes/SceneryStackManager.kt
- src/main/kotlin/graphics/scenery/volumes/TransformedBufferedSimpleStack3D.kt
- src/main/kotlin/graphics/scenery/volumes/TransformedMultiResolutionStack3D.kt
- src/main/kotlin/graphics/scenery/volumes/TransformedSimpleStack3D.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/main/kotlin/graphics/scenery/volumes/VolumeManager.kt
- src/main/kotlin/graphics/scenery/volumes/VolumeShaderFactory.kt
- src/test/kotlin/graphics/scenery/tests/examples/advanced/VRVolumeCroppingExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/compute/CustomVolumeManagerExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/BDVExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/BigAndSmallVolumeExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/NetworkVolumeExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/OrthoViewExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/OutOfCoreRAIExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/RAIExample.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/TransferFunctionEditorExample.kt
This PR reverts to the official bigvolumeviewer, in version 0.3.1. Thanks @tpietzsch for merging our PRs and the new version, and thanks @ctrueden for the work on this PR 🥳 Fixes #385.
> Revert bigvolumeviewer to official version and remove deprecated APIs

- src/main/kotlin/graphics/scenery/ui/RangeSliderUI.kt
- src/main/kotlin/graphics/scenery/ui/SwingBridgeFrame.kt
- src/main/kotlin/graphics/scenery/volumes/HasTransferFunction.kt
- src/main/kotlin/graphics/scenery/volumes/TransferFunctionEditor.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
- src/test/kotlin/graphics/scenery/tests/examples/volumes/TransferFunctionEditorExample.kt
This PR changes the Mig-Layout of the TransferFunctionEditor to support dynamic window resizes down to 0,0
There was also a major bug, where adding a control point, when the window size was smaller then the internal minimum chart draw size, results in a control point not at mouse-position. This bug was fixed by setting the minimum draw-sizes of the ChartPanel to 0.
Also: Refactored the panel adding to the SwingBridgeFrame, which now packs and sets visibility as well to simplify the API
> TransferFunctionEditor -Mig-Layout change to support dynamic resizes + Major BugFix

- .github/workflows/build.yml
- buildSrc/src/main/kotlin/scenery/base.gradle.kts
This PR adjusts the pagefile size on the Github Actions Windows runners, to avoid random out-of-memory errors for memory-intensive unit tests.
> CI: Adjust pagefile size on Windows to avoid unnecessary noise

- src/main/kotlin/graphics/scenery/primitives/Cylinder.kt
- src/test/kotlin/graphics/scenery/tests/unit/VolumeMeasuererTests.kt
Fixes #556 
Refactors the code to work with geometryType Triangles instead of Triangle_Strip to support fan-like face structure of top and bottom caps, default is off (can be turned on with `fillCaps=true`). Normal interpolation can be turned on by passing the attribute `smoothSides`, default is false.
Flat shading with filled caps:
Smooth shading & texture mapping:
> Cylinder: Add top and bottom lids, make smooth shading optional

- build.gradle.kts
- src/main/kotlin/graphics/scenery/SceneryBase.kt
- src/main/kotlin/graphics/scenery/repl/REPL.kt
This PR fixes an issue where the REPL's startup code would not be executed when the REPL is first shown. It also removes the dependency on the Nashorn-based JavaScript interpreter, as it's not used in scenery anymore, and deprecated in OpenJDK.
> REPL: Fix issue where startup script would not be executed

- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanDevice.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
This PR fixes a Vulkan validation issue where the VK_KHR_portability_subset was not correctly added. The extension needs to be added if it is supported by the device.
> Correctly include VK_KHR_portability_subset extension

- build.gradle.kts
- gradle.properties
This PR bumps lwjgl and lwjgl3-awt to the latest official versions.
> Gradle: Bump lwjgl to 3.3.2 and lwjgl3-awt to official repo version

- src/main/kotlin/graphics/scenery/OrientedBoundingBox.kt
- src/main/kotlin/graphics/scenery/attribute/spatial/DefaultSpatial.kt
- src/main/kotlin/graphics/scenery/attribute/spatial/Spatial.kt
- src/test/kotlin/graphics/scenery/tests/examples/basic/IntersectionExample.kt
This PR extends the `intersects()` method to perform actual oriented bounding box tests, not just bounding sphere tests, as currently performed.
https://github.com/scenerygraphics/scenery/assets/586495/4fc7c125-7110-4e69-99c9-d5cabb7bc79f
https://github.com/scenerygraphics/scenery/assets/586495/5ee394f9-854d-47fb-8d50-53057b7c85bb
> Finer-grained intersection testing for Nodes

- src/main/kotlin/graphics/scenery/backends/vulkan/SwingSwapchain.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/utils/SceneryJPanel.kt
This PR resolves and issue where vsync would not be enabled/disabled correctly if a swapchain other than the default VulkanSwapchain was used.
> VulkanRenderer: Correctly hand over vsync parameter to swapchains

- src/main/kotlin/graphics/scenery/Mesh.kt
- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
As groups (`g`) and objects (`o`) are used somewhat inconsistently in OBJ files, this PR introduces a new heuristic in the OBJ parser that tries to figure out what convention is used. This fixes e.g. the loading of the Oculus Quest (2) model file textures from SteamVR.
> OBJ object/group conventions

- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanDevice.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanObjectState.kt
This PR fixes a problem in Vulkan descriptor pool allocation, which lead to the problem that no more descriptors could be allocated.
> VulkanDevice: Fix descriptor pool allocation

- src/main/kotlin/graphics/scenery/backends/ShaderPackage.kt
- src/main/kotlin/graphics/scenery/backends/Shaders.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanShaderModule.kt
This PR improves hot reloading of shaders:
* when any shader file is requested, the shader compiler will look for that shader in the current working directory, and in the `shaders/` subdirectory - the first file found will be watched for changes and reloaded on-the-fly
* hot-reloadable shaders from the filesystem will only be marked as stale if their compilation succeeds
* hot-reloadable shaders will not be cached
Nice hack for Linux and macOS: symlink `src/main/resources/graphics/scenery/backends/shaders` to `./shaders`, so all of scenery's default shaders become hot-reloadable.
> Improve shader hot reloading

- .github/workflows/build.yml
With this PR, we use gradle-build-action to allow for wrapper caching in Github Actions. This should speed up the GHA build.
> Github Actions: Use gradle-build-action to allow for wrapper caching

- build.gradle.kts
- buildSrc/src/main/kotlin/scenery/base.gradle.kts
- buildSrc/src/main/kotlin/scenery/publish.gradle.kts
plus:
- replaced deprecated `buildDir` with `layout.buildDirectory`
- simplified some constructs for adding jvm args
- using the available `inceptionYear` property instead of a generic entry in properties
> Implemented Kotlin Assignment Operator

- build.gradle.kts
- gradle.properties
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanFramebuffer.kt
This PR bumps Kotlin to 1.9.21, dokka to 1.9.10, and lwjgl 3.3.3. It also fixes a missing dependency that was biting sciview in conjunction with jgo.
> Gradle: Bump Kotlin to 1.9.21, and lwjgl to 3.3.3

- src/main/kotlin/graphics/scenery/backends/RenderConfigReader.kt
This PR fixes an issue where an old Jackson API was used that is not supported anymore.
> RenderConfigReader: Adjust to new Jackson Kotlin API

- .github/workflows/build.yml
- .gitlab-ci.yml
- build.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- gradlew
This PR switches the build to Java 21 by default, and will also generate packages with Java 21 bytecode version. In addition, all Gitlab CI builds now use [the same Docker image](https://hub.docker.com/layers/scenerygraphics/nvidia-vulkan/1.3.261.1-ubuntu20.04-v3/images/sha256-ea8c95427e2db6a1623fc989d1251732844a48bbffa276f162cb93ac94080863?context=explore), which includes all prerequisites, such as the JDK, Vulkan SDK, etc. Before, the non-GPU builds used a default Ubuntu image, which required package installations on each run.
> Switch default build to Java 21

- src/main/kotlin/graphics/scenery/backends/UBO.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
Simply using `FloatArray.hashCode()` caused the issue that UBO hashing in order to check for updates got defeated by new float arrays with the same contents being allocated. This happened because bigvolumeviewer copies float arrays behind the scenes when assigning them as a uniform. This PR replaces hashCode() calls on FloatArray and IntArray with contentHashCode(), which does not take the specific reference into account, but only the content of the array. 
In addition, this PR also removes repeated allocations of the slicing equation array in Volume, and allocates the array only once.
> Don't let volumes defeat push mode

- src/main/kotlin/graphics/scenery/numerics/Random.kt
- src/test/kotlin/graphics/scenery/tests/examples/stresstests/ExampleRunner.kt
Argos at the moment still produces too many false positives. This PR aims to solve this, via:
* enabling `Random` to be re-seeded with a given seed that is either given, or determined from the the `scenery.RandomSeed` system property
* re-seeding `Random`'s PRNG for each run of an example, in order to have a deterministic sequences of pseudorandom numbers
> Stabilise Argos' Screenshot evaluation

- src/main/kotlin/graphics/scenery/PointLight.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanScenePass.kt
This PR fixes an issue where Nodes which delegate rendering (such as Volumes) would be left with initialised metadata (from the delegate), but would themselves not be marked initialised. This leads to an issue where they'd cause constant updates and defeat push mode.
To make push mode defeat issues more easily debuggable in the future, this PR also adds `VulkanRenderer.pushModeDefeats`, which keeps track of the reasons for the last five push mode defeats.
> Fix uninitialised delegated Nodes

- src/main/resources/graphics/scenery/volumes/AccumulateBlockVolume.frag
- src/main/resources/graphics/scenery/volumes/AccumulateSimpleVolume.frag
- src/main/resources/graphics/scenery/volumes/BDVVolume.frag
- src/test/resources/graphics/scenery/tests/examples/compute/ComputeVolume.comp
As noted by @moreApi , the opacity adjustment currently used in volume raycasting makes volumes too transparent. This PR adjusts the opacity relative to a predefined `standardStepSize` - equal to half the side length of a voxel in world space - which alleviates the issue while maintaining the benefits of adjusting the opacity when required.
According to the book Real-Time Volume Graphics (https://dl.acm.org/doi/pdf/10.1145/1103900.1103929 see page 30), opacity adjustment does not need to be applied if the step size is always constant, because the impact of taking finite non-infinitesimal steps is effectively incorporated into the manually defined transfer function. When steps of different size are to be taken, however, the opacity needs to be adjusted to ensure that the overall intensity …
> Improving opacity adjustment in volume rendering

- README.md
- gradle.properties
This PR prepares for the 0.11.0 release by:
* bumping the scijava parent POM to 37.0.0
* bumping Kotlin to 1.9.23
> 0.11.0 preparations

- src/main/kotlin/graphics/scenery/SceneryBase.kt
The gracePeriod variable only decreases in the main loop while it is
looping. But the `shouldClose = true` causes the main loop to stop
looping. So the gracePeriod only had time to decrement once (to 59),
at which point the while loop here in the `close()` function gets stuck.
It may be the case that this looping was only necessary for the OpenGL
renderer anyway, which is no longer an issue, so we can simplify now.
> Remove waiting period when closing

- src/main/kotlin/graphics/scenery/Camera.kt
- src/main/kotlin/graphics/scenery/DefaultNode.kt
- src/main/kotlin/graphics/scenery/DetachedHeadCamera.kt
- src/main/kotlin/graphics/scenery/DirectionalLight.kt
- src/main/kotlin/graphics/scenery/InstancedNode.kt
- src/main/kotlin/graphics/scenery/Mesh.kt
- src/main/kotlin/graphics/scenery/Node.kt
- src/main/kotlin/graphics/scenery/PointLight.kt
- src/main/kotlin/graphics/scenery/RichNode.kt
- src/main/kotlin/graphics/scenery/atomicsimulations/AtomicSimulation.kt
- src/main/kotlin/graphics/scenery/backends/RendererFlags.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanNodeHelpers.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRendererMetadata.kt
- src/main/kotlin/graphics/scenery/backends/vulkan/VulkanScenePass.kt
- src/main/kotlin/graphics/scenery/primitives/PointCloud.kt
This PR cleans up some cruft from the Node interface and unifies state flags. Further, it renames VulkanObjectState to VulkanRendererMetadata.
> Clean up Node state variables and Node interface

- src/main/resources/graphics/scenery/volumes/ComputeHistogram.comp
The largest change in the history of scenery. 
Fixes the generation of 16bit volumes on the gpu.
> ComputeHistogram.comp: Fix 16 bit histogram calculation on gpu

- src/main/resources/graphics/scenery/backends/shaders/DeferredInstancedColor.frag
- src/main/resources/graphics/scenery/backends/shaders/DeferredInstancedColor.vert
This PR adds a new fragment & vertex shader type to be used for coloring individual instances of instanced geometry.
The syntax for writing the color attribute is:
```Kotlin
InstancedNode.Instance.instancedProperties["Color"] = { Vector4f(1f) }
```
The code is largely taken from [this](https://github.com/scenerygraphics/sciview/blob/main/src/main/resources/sc/iview/commands/demo/animation/ParticleDemo.frag) and [this](https://github.com/scenerygraphics/sciview/blob/main/src/main/resources/sc/iview/commands/demo/animation/ParticleDemo.vert) ParticleDemo shader in Sciview.
> add DeferredInstancedColor shaders

- src/test/kotlin/graphics/scenery/tests/examples/basic/AtmosphereExample.kt
The default sun position was influenced by local time, thus screwing with the Argos tests for the `AtmosphereExample`.
This PR solves this bug by passing a fixed sun position vector to the constructur.
> Pass a fixed sun position to the Atmosphere constructor for reproducability

- src/main/kotlin/graphics/scenery/primitives/Atmosphere.kt
Azimuth range was -180-180, which conflicted with the more common range 0-360 that is set as a sciview property for the inspector.
Declination calculation has also been fix and show be more accurate now.
> Fix atmosphere azimuth range and declination formula

- gradle.properties
This PR bumps Kotlin to 2.0.0 and Dokka to 1.9.23.
> Bump Kotlin to 2.0.0, Dokka to 1.9.23

- src/main/kotlin/graphics/scenery/volumes/Colormap.kt
- src/main/kotlin/graphics/scenery/volumes/ColormapPanel.kt
Colormap.sample would go out of bounds. It was also broken for odd h values. [Issue #750](https://github.com/scenerygraphics/scenery/issues/750)
Made a hot fix for generating an image form the ColormapEditor the image was missing 10px so depending on how large the editor was displayed the resulting Colormap always returned black. [Issue #757](https://github.com/scenerygraphics/scenery/issues/757)
If this looks ok I can improve it.
> Fixed the sample method. 

- src/main/kotlin/graphics/scenery/Camera.kt
This adds a new `centering` parameter to `Camera.showMessage()` (default = false) that attempts to center the text based on message length (bounding boxes are not available for textboards, so can't use those). The scaling factor is a bit eyeballed, but it seems to work for the text sizes I currently use.
> Allow to center camera messages

- src/main/resources/graphics/scenery/backends/shaders/DSSDO.frag
- src/main/resources/graphics/scenery/backends/shaders/DSSDOBlur.frag
This PR fixes an issue in the DSSDO shaders introduced in #594. There, the order of sampled attachments was wrong, causing the DSSDO shader to sample depth from the emissions texture, leading to visual artifacts.
> DSSDO: Fix wrong attachment order for samples

- gradle.properties
- src/main/kotlin/graphics/scenery/backends/RenderConfigReader.kt
This PR bumps the dependency on the scijava parent POM to 39.0.0, and also bumps Kotlin to 2.0.21, while removing a spurious import from RenderConfigReader.
> Bump scijava parent POM to 39.0.0

- src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
- src/main/kotlin/graphics/scenery/volumes/RAIVolume.kt
This PR adds `initalized = false` to `OpenVRHMD.close()` before calling the shutdown logic to prevent the renderer from accessing memory that doesn't exist anymore.
> OpenVRHMD safe shutdown

- src/main/kotlin/graphics/scenery/volumes/BufferedVolume.kt
- src/main/kotlin/graphics/scenery/volumes/DisplayRangeEditor.kt
- src/main/kotlin/graphics/scenery/volumes/DummyVolume.kt
- src/main/kotlin/graphics/scenery/volumes/HasTransferFunction.kt
- src/main/kotlin/graphics/scenery/volumes/Volume.kt
Improve naming of hasTransferFunction.range property to make its function clear and avoid confusion with minDisplayRange and maxDisplayRange
> Improve naming of hasTransferFunction.range property to make its function clear and avoid confusion with minDisplayRange and maxDisplayRange
